# Generated by Django 4.2.4 on 2023-09-02 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('car_model', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('gos_number', models.CharField(max_length=255)),
                ('fuel_type', models.CharField(max_length=255)),
                ('volume', models.FloatField()),
                ('price', models.FloatField()),
                ('payment', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('delivery_time', models.TimeField(default=datetime.time(0, 0))),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
