# Generated by Django 4.2.4 on 2023-09-05 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prime', '0005_alter_city_options_alter_client_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['id'], 'verbose_name': 'Города', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='fuel',
            options={'ordering': ['id'], 'verbose_name': 'Типы топлива', 'verbose_name_plural': 'Типы топлива'},
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='client',
            name='car_model',
            field=models.CharField(max_length=255, verbose_name='Авто'),
        ),
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(max_length=255, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='client',
            name='color',
            field=models.CharField(max_length=255, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='client',
            name='delivery_time',
            field=models.DateTimeField(verbose_name='Дата доставки'),
        ),
        migrations.AlterField(
            model_name='client',
            name='fuel_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prime.fuel', verbose_name='Топливо'),
        ),
        migrations.AlterField(
            model_name='client',
            name='gos_number',
            field=models.CharField(max_length=255, verbose_name='Гос-номер'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='client',
            name='payment',
            field=models.CharField(max_length=255, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=255, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='client',
            name='price',
            field=models.FloatField(verbose_name='Сумма к оплате'),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.BooleanField(verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='client',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='client',
            name='volume',
            field=models.FloatField(verbose_name='Объем поставки'),
        ),
        migrations.AlterField(
            model_name='fuel',
            name='price',
            field=models.FloatField(verbose_name='Цена (1 л.)'),
        ),
        migrations.AlterField(
            model_name='fuel',
            name='remaining_volume',
            field=models.FloatField(verbose_name='Объем на складе'),
        ),
        migrations.AlterField(
            model_name='fuel',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='fuel',
            name='type',
            field=models.CharField(max_length=255, verbose_name='Тип топлива'),
        ),
    ]
